In [2]:
import pandas as pd
import pickle
from tensorflow.keras.models import load_model

In [3]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
ann_model = load_model("model.h5")

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [13]:
df = pd.DataFrame([input_data.values()], columns = input_data.keys())
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [18]:
## convert the gender
with open("labelencoder.pkl", "rb") as f:
    labelencoder = pickle.load(f)

with open("ohe.pkl", "rb") as f:
    ohe = pickle.load(f)

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

In [19]:
df["Gender"] = labelencoder.transform(df["Gender"])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [23]:
df_geography = ohe.transform([df["Geography"]])
df_geography

e:\Python\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 3)>

In [24]:
df_geography.toarray()

array([[1., 0., 0.]])

In [33]:
df_geography = pd.DataFrame(df_geography.toarray(), columns = ohe.get_feature_names_out())
df_geography

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [34]:
df = pd.concat([df.drop(["Geography"], axis = 1), df_geography], axis = 1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [38]:
scaled_X = scaler.transform(df)
scaled_X

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [40]:
value = ann_model.predict(x=scaled_X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

In [41]:
if value > 0.5:
    print("He is going to exit")
else:
    print("He is not going to exit")

He is not going to exit